import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"最佳实践","description":"","frontmatter":{},"headers":[],"relativePath":"advanced/best-practices.md","filePath":"advanced/best-practices.md"}');
const _sfc_main = { name: "advanced/best-practices.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="最佳实践" tabindex="-1">最佳实践 <a class="header-anchor" href="#最佳实践" aria-label="Permalink to &quot;最佳实践&quot;">​</a></h1><p>本节介绍使用 Link Exchange Badges SDK 的最佳实践。</p><h2 id="项目结构" tabindex="-1">项目结构 <a class="header-anchor" href="#项目结构" aria-label="Permalink to &quot;项目结构&quot;">​</a></h2><h3 id="_1-配置管理" tabindex="-1">1. 配置管理 <a class="header-anchor" href="#_1-配置管理" aria-label="Permalink to &quot;1. 配置管理&quot;">​</a></h3><p>创建集中的配置管理：</p><div class="language-typescript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// config/badges.ts</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">export</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> badgesConfig</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  development: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    source: process.env.</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">NEXT_PUBLIC_BADGES_URL_DEV</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> ||</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;http://localhost:8080/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    siteId: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;my-app-dev&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    environment: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;development&#39;</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> as</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> const</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    cache: { enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">false</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  },</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  staging: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://staging-cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    siteId: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;my-app-staging&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    environment: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;staging&#39;</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> as</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> const</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    cache: { enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, ttlMs: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">5</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  },</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  production: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    siteId: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;my-app&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    environment: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;production&#39;</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> as</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> const</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    cache: { enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, ttlMs: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">30</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    security: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      allowedLinkDomains: [</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;github.com&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;npmjs.com&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      allowedImageDomains: [</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;img.shields.io&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;github.com&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">export</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> getBadgesConfig</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> env</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (process.env.</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">NODE_ENV</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> ||</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;development&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">as</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> keyof</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> typeof</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> badgesConfig</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> badgesConfig[env]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br></div></div><h3 id="_2-组件封装" tabindex="-1">2. 组件封装 <a class="header-anchor" href="#_2-组件封装" aria-label="Permalink to &quot;2. 组件封装&quot;">​</a></h3><p>创建可复用的组件：</p><div class="language-tsx line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">tsx</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// components/BadgesSection.tsx</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;use client&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { memo } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;react&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { LinkExchange } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/react&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { getBadgesConfig } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@/config/badges&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">interface</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> BadgesSectionProps</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">  group</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> string</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">  locale</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> string</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">  className</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> string</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">export</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> BadgesSection</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> memo</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> BadgesSection</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">({</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">  group</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">  locale</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">  className</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">:</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> BadgesSectionProps</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> config</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> getBadgesConfig</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">LinkExchange</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      {</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">...</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">config}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">      group</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{group}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">      locale</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{locale}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">      className</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{className}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">      telemetry</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">        onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;[Badges]&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, event.type, event)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">          // 发送到分析平台</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">          if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (window.analytics) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">            window.analytics.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">track</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(event.type, event)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      }}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  )</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br><span class="line-number">32</span><br><span class="line-number">33</span><br><span class="line-number">34</span><br><span class="line-number">35</span><br><span class="line-number">36</span><br><span class="line-number">37</span><br><span class="line-number">38</span><br><span class="line-number">39</span><br></div></div><h2 id="性能优化" tabindex="-1">性能优化 <a class="header-anchor" href="#性能优化" aria-label="Permalink to &quot;性能优化&quot;">​</a></h2><h3 id="_1-懒加载" tabindex="-1">1. 懒加载 <a class="header-anchor" href="#_1-懒加载" aria-label="Permalink to &quot;1. 懒加载&quot;">​</a></h3><p>延迟加载 SDK：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 等待用户滚动到徽章区域</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> observer</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> new</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> IntersectionObserver</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">((</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">entries</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  entries.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">forEach</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">entry</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (entry.isIntersecting) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;@link-exchange/react&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">).</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">then</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(({ </span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">LinkExchange</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> }) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">        // 渲染组件</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      observer.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">unobserve</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(entry.target)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">observer.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">observe</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(document.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">querySelector</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">))</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><h3 id="_2-代码分割" tabindex="-1">2. 代码分割 <a class="header-anchor" href="#_2-代码分割" aria-label="Permalink to &quot;2. 代码分割&quot;">​</a></h3><p>使用动态导入：</p><div class="language-tsx line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">tsx</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> dynamic </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;next/dynamic&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> LinkExchange</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> dynamic</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  () </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;@link-exchange/react&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">).</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">then</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">mod</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> mod.LinkExchange),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    loading</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: () </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">div</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;Loading badges...&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">div</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    ssr: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">false</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><h3 id="_3-缓存策略" tabindex="-1">3. 缓存策略 <a class="header-anchor" href="#_3-缓存策略" aria-label="Permalink to &quot;3. 缓存策略&quot;">​</a></h3><p>合理的缓存配置：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> cacheConfig</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  // 开发环境：短缓存，便于调试</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  development: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    ttlMs: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">1</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> // 1 分钟</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  },</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  // 生产环境：长缓存，提升性能</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  production: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    ttlMs: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> // 1 小时</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><h3 id="_4-资源预加载" tabindex="-1">4. 资源预加载 <a class="header-anchor" href="#_4-资源预加载" aria-label="Permalink to &quot;4. 资源预加载&quot;">​</a></h3><p>在 HTML 头部预加载关键资源：</p><div class="language-html line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">html</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">head</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  &lt;!-- 预连接到 CDN --&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">link</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> rel</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;preconnect&quot;</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> href</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://cdn.example.com&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  &lt;!-- DNS 预解析 --&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">link</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> rel</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;dns-prefetch&quot;</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> href</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://cdn.example.com&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  &lt;!-- 预加载配置 --&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">link</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> rel</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;preload&quot;</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> href</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://cdn.example.com/badges.json&quot;</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> as</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;fetch&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  &lt;!-- 预加载图片 --&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">link</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> rel</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;preload&quot;</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> as</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;image&quot;</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> href</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://img.shields.io/badge/GitHub-100000?logo=github&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">head</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br></div></div><h2 id="安全实践" tabindex="-1">安全实践 <a class="header-anchor" href="#安全实践" aria-label="Permalink to &quot;安全实践&quot;">​</a></h2><h3 id="_1-环境变量" tabindex="-1">1. 环境变量 <a class="header-anchor" href="#_1-环境变量" aria-label="Permalink to &quot;1. 环境变量&quot;">​</a></h3><p>使用环境变量管理敏感配置：</p><div class="language-bash line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"># .env.development</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">NEXT_PUBLIC_BADGES_URL</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">http://localhost:8080/badges.json</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">NEXT_PUBLIC_SITE_ID</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">my-app-dev</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"># .env.production</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">NEXT_PUBLIC_BADGES_URL</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">https://cdn.example.com/badges.json</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">NEXT_PUBLIC_SITE_ID</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">my-app</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h3 id="_2-安全白名单" tabindex="-1">2. 安全白名单 <a class="header-anchor" href="#_2-安全白名单" aria-label="Permalink to &quot;2. 安全白名单&quot;">​</a></h3><p>生产环境必须配置白名单：</p><div class="language-typescript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> getSecurityConfig</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (process.env.</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">NODE_ENV</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> ===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;production&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      allowedLinkDomains: [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">        &#39;github.com&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">        &#39;npmjs.com&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">        &#39;vercel.com&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      ],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      allowedImageDomains: [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">        &#39;img.shields.io&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">        &#39;github.com&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">        &#39;npmjs.com&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      ]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><h3 id="_3-csp-配置" tabindex="-1">3. CSP 配置 <a class="header-anchor" href="#_3-csp-配置" aria-label="Permalink to &quot;3. CSP 配置&quot;">​</a></h3><p>配置内容安全策略：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// next.config.js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> ContentSecurityPolicy</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> \`</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">  default-src &#39;self&#39;;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">  script-src &#39;self&#39; &#39;unsafe-eval&#39; &#39;unsafe-inline&#39; https://cdn.example.com;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">  img-src &#39;self&#39; data: https: blob:;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">  connect-src &#39;self&#39; https://cdn.example.com;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">\`</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h2 id="错误处理" tabindex="-1">错误处理 <a class="header-anchor" href="#错误处理" aria-label="Permalink to &quot;错误处理&quot;">​</a></h2><h3 id="_1-优雅降级" tabindex="-1">1. 优雅降级 <a class="header-anchor" href="#_1-优雅降级" aria-label="Permalink to &quot;1. 优雅降级&quot;">​</a></h3><p>使用快照配置作为 fallback：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> FALLBACK_CONFIG</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  configVersion: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;1&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  schemaVersion: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;1.0.0&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  updatedAt: </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">new</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Date</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">().</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">toISOString</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  badges: [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      id: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;github&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      name: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;GitHub&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      renderType: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;image&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      imageUrl: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://img.shields.io/badge/GitHub-100000?logo=github&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      linkUrl: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://github.com&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  ]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  fallback: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    snapshot: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">FALLBACK_CONFIG</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    silent: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">false</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br></div></div><h3 id="_2-错误边界" tabindex="-1">2. 错误边界 <a class="header-anchor" href="#_2-错误边界" aria-label="Permalink to &quot;2. 错误边界&quot;">​</a></h3><p>React 中使用错误边界：</p><div class="language-tsx line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">tsx</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">class</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> BadgesErrorBoundary</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> extends</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Component</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  { </span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">children</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">:</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> ReactNode</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  { </span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">hasError</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">:</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> boolean</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt; {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  constructor</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">props</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">    super</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(props)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">    this</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">.state </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { hasError: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">false</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  static</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> getDerivedStateFromError</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { hasError: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  render</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">this</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">.state.hasError) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">div</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;徽章暂时无法显示&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">div</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> this</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">.props.children</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br></div></div><h2 id="监控与分析" tabindex="-1">监控与分析 <a class="header-anchor" href="#监控与分析" aria-label="Permalink to &quot;监控与分析&quot;">​</a></h2><h3 id="_1-遥测集成" tabindex="-1">1. 遥测集成 <a class="header-anchor" href="#_1-遥测集成" aria-label="Permalink to &quot;1. 遥测集成&quot;">​</a></h3><p>集成分析平台：</p><div class="language-typescript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { analytics } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@/lib/analytics&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> setupTelemetry</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: process.env.</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">NODE_ENV</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> ===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;production&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">:</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> SDKEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">      // 发送到分析平台</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      analytics.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">track</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(event.type, event)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">      // 错误事件发送到 Sentry</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (event.type.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">includes</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;failed&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">||</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> event.type.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">includes</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;error&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        Sentry.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">captureException</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">new</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Error</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(event.type), {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          tags: { component: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          extra: event</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br></div></div><h3 id="_2-性能监控" tabindex="-1">2. 性能监控 <a class="header-anchor" href="#_2-性能监控" aria-label="Permalink to &quot;2. 性能监控&quot;">​</a></h3><p>监控关键指标：</p><div class="language-typescript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> trackPerformance</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> startTime</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> performance.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">now</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">:</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> SDKEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (event.type </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;render_success&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">        const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> duration</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> performance.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">now</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">-</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> startTime</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">        // 发送到性能监控</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">        if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (window.gtag) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">          gtag</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;event&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;timing_complete&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">            name: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;badge_render&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">            value: Math.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">round</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(duration)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br></div></div><h2 id="测试" tabindex="-1">测试 <a class="header-anchor" href="#测试" aria-label="Permalink to &quot;测试&quot;">​</a></h2><h3 id="_1-单元测试" tabindex="-1">1. 单元测试 <a class="header-anchor" href="#_1-单元测试" aria-label="Permalink to &quot;1. 单元测试&quot;">​</a></h3><p>编写单元测试：</p><div class="language-tsx line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">tsx</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { render, screen } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@testing-library/react&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { BadgesSection } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;./BadgesSection&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">describe</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;BadgesSection&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, () </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  it</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;renders without crashing&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, () </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    render</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(&lt;</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">BadgesSection</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> group</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;partners&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> /&gt;)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    expect</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(screen.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">getByRole</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;generic&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)).</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">toBeInTheDocument</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  })</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  it</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;passes correct props&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, () </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    render</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(&lt;</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">BadgesSection</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> group</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;technologies&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> /&gt;)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">    // 验证 props 传递</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><h3 id="_2-集成测试" tabindex="-1">2. 集成测试 <a class="header-anchor" href="#_2-集成测试" aria-label="Permalink to &quot;2. 集成测试&quot;">​</a></h3><p>测试完整流程：</p><div class="language-typescript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { mount } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/core&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">describe</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;Badge Integration&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, () </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  it</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;loads and renders badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">async</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> () </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> result</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> await</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    })</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    expect</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(result).</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">toBeDefined</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    expect</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(result.unmount).</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">toBeInstanceOf</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(Function)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    result.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">unmount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><h2 id="文档" tabindex="-1">文档 <a class="header-anchor" href="#文档" aria-label="Permalink to &quot;文档&quot;">​</a></h2><h3 id="_1-代码注释" tabindex="-1">1. 代码注释 <a class="header-anchor" href="#_1-代码注释" aria-label="Permalink to &quot;1. 代码注释&quot;">​</a></h3><p>编写清晰的注释：</p><div class="language-typescript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">/**</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> * 徽章配置</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> *</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> * </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">@example</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> * \`\`\`tsx</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> * &lt;BadgesSection group=&quot;partners&quot; /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> * \`\`\`</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> */</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">export</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> BadgesSection</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">({ </span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">group</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> }</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">:</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Props</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  // ...</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h3 id="_2-readme" tabindex="-1">2. README <a class="header-anchor" href="#_2-readme" aria-label="Permalink to &quot;2. README&quot;">​</a></h3><p>维护项目文档：</p><div class="language-markdown line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">markdown</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF", "font-weight": "bold" })}"># My Project</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF", "font-weight": "bold" })}">## 徽章配置</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">本项目使用 Link Exchange Badges 展示合作伙伴徽章。</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF", "font-weight": "bold" })}">### 配置</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">详见 </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">\`config/badges.ts\`</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF", "font-weight": "bold" })}">### 使用</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">\\\`\\\`\\\`</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">tsx</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">import { BadgesSection } from &#39;@/components/BadgesSection&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;BadgesSection group=&quot;partners&quot; /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">\\\`\\\`\\\`</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><h2 id="版本管理" tabindex="-1">版本管理 <a class="header-anchor" href="#版本管理" aria-label="Permalink to &quot;版本管理&quot;">​</a></h2><h3 id="_1-配置版本控制" tabindex="-1">1. 配置版本控制 <a class="header-anchor" href="#_1-配置版本控制" aria-label="Permalink to &quot;1. 配置版本控制&quot;">​</a></h3><p>使用版本号管理配置：</p><div class="language- line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span>https://cdn.example.com/badges.v1.json</span></span>
<span class="line"><span>https://cdn.example.com/badges.v2.json</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h3 id="_2-渐进式更新" tabindex="-1">2. 渐进式更新 <a class="header-anchor" href="#_2-渐进式更新" aria-label="Permalink to &quot;2. 渐进式更新&quot;">​</a></h3><p>逐步推出新配置：</p><div class="language-typescript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> configVersion</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> Math.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">random</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 0.1</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> ?</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;v2&#39;</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> :</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;v1&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">\`https://cdn.example.com/badges.\${</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">configVersion</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">}.json\`</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h2 id="可访问性" tabindex="-1">可访问性 <a class="header-anchor" href="#可访问性" aria-label="Permalink to &quot;可访问性&quot;">​</a></h2><h3 id="_1-语义化-html" tabindex="-1">1. 语义化 HTML <a class="header-anchor" href="#_1-语义化-html" aria-label="Permalink to &quot;1. 语义化 HTML&quot;">​</a></h3><p>使用正确的 HTML 标签：</p><div class="language-tsx line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">tsx</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">LinkExchange</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  as</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;footer&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  source</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://cdn.example.com/badges.json&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">/&gt;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="_2-替代文本" tabindex="-1">2. 替代文本 <a class="header-anchor" href="#_2-替代文本" aria-label="Permalink to &quot;2. 替代文本&quot;">​</a></h3><p>确保所有徽章都有 alt 文本：</p><div class="language-json line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  &quot;badges&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;alt&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;GitHub - 代码托管平台&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  ]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h3 id="_3-键盘导航" tabindex="-1">3. 键盘导航 <a class="header-anchor" href="#_3-键盘导航" aria-label="Permalink to &quot;3. 键盘导航&quot;">​</a></h3><p>支持键盘导航：</p><div class="language-css line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">css</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">.badge-link:focus</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  outline</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">2</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">px</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> solid</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> #667eea</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  outline-offset</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">2</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">px</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h2 id="部署" tabindex="-1">部署 <a class="header-anchor" href="#部署" aria-label="Permalink to &quot;部署&quot;">​</a></h2><h3 id="_1-环境检查" tabindex="-1">1. 环境检查 <a class="header-anchor" href="#_1-环境检查" aria-label="Permalink to &quot;1. 环境检查&quot;">​</a></h3><p>部署前检查配置：</p><div class="language-typescript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> validateProductionConfig</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> config</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> getBadgesConfig</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (process.env.</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">NODE_ENV</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> ===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;production&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">!</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">config.security) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      throw</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> new</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Error</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;安全白名单未配置&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">!</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">config.telemetry?.enabled) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">warn</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;生产环境建议启用遥测&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> config</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><h3 id="_2-ci-cd" tabindex="-1">2. CI/CD <a class="header-anchor" href="#_2-ci-cd" aria-label="Permalink to &quot;2. CI/CD&quot;">​</a></h3><p>在 CI/CD 中验证：</p><div class="language-yaml line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"># .github/workflows/deploy.yml</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">- </span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">name</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">Validate badges config</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#85E89D" })}">  run</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">|</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">    npm run validate-badges-config</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h2 id="总结" tabindex="-1">总结 <a class="header-anchor" href="#总结" aria-label="Permalink to &quot;总结&quot;">​</a></h2><h3 id="关键原则" tabindex="-1">关键原则 <a class="header-anchor" href="#关键原则" aria-label="Permalink to &quot;关键原则&quot;">​</a></h3><ol><li><strong>性能优先</strong>：合理使用缓存、懒加载、代码分割</li><li><strong>安全第一</strong>：配置白名单、使用 HTTPS、验证输入</li><li><strong>错误容忍</strong>：优雅降级、错误边界、重试机制</li><li><strong>监控完善</strong>：遥测追踪、性能监控、错误上报</li><li><strong>测试充分</strong>：单元测试、集成测试、端到端测试</li><li><strong>文档清晰</strong>：代码注释、README、API 文档</li></ol><h3 id="检查清单" tabindex="-1">检查清单 <a class="header-anchor" href="#检查清单" aria-label="Permalink to &quot;检查清单&quot;">​</a></h3><p>部署前确认：</p><ul><li>[ ] 配置 URL 使用 HTTPS</li><li>[ ] 安全白名单已配置</li><li>[ ] 缓存策略已优化</li><li>[ ] 遥测已集成</li><li>[ ] 错误处理已完善</li><li>[ ] 测试已通过</li><li>[ ] 文档已更新</li></ul><h2 id="下一步" tabindex="-1">下一步 <a class="header-anchor" href="#下一步" aria-label="Permalink to &quot;下一步&quot;">​</a></h2><ul><li><a href="/LinkExchangeBadges/advanced/telemetry.html">遥测与分析</a></li><li><a href="/LinkExchangeBadges/advanced/security.html">安全性</a></li><li><a href="/LinkExchangeBadges/advanced/troubleshooting.html">故障排查</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("advanced/best-practices.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const bestPractices = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  bestPractices as default
};
