import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"缓存策略","description":"","frontmatter":{},"headers":[],"relativePath":"docs/guide/caching.md","filePath":"docs/guide/caching.md"}');
const _sfc_main = { name: "docs/guide/caching.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="缓存策略" tabindex="-1">缓存策略 <a class="header-anchor" href="#缓存策略" aria-label="Permalink to &quot;缓存策略&quot;">​</a></h1><p>Link Exchange Badges SDK 内置了智能缓存系统，可以显著提升性能和用户体验。</p><h2 id="缓存机制" tabindex="-1">缓存机制 <a class="header-anchor" href="#缓存机制" aria-label="Permalink to &quot;缓存机制&quot;">​</a></h2><h3 id="工作原理" tabindex="-1">工作原理 <a class="header-anchor" href="#工作原理" aria-label="Permalink to &quot;工作原理&quot;">​</a></h3><p>SDK 使用以下缓存策略：</p><ol><li><strong>Cache-First</strong>：优先使用缓存</li><li><strong>TTL 验证</strong>：检查缓存是否过期</li><li><strong>Stale Fallback</strong>：网络失败时使用过期缓存</li><li><strong>LocalStorage</strong>：使用浏览器 localStorage 存储</li></ol><h3 id="缓存流程" tabindex="-1">缓存流程 <a class="header-anchor" href="#缓存流程" aria-label="Permalink to &quot;缓存流程&quot;">​</a></h3><div class="language- line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span>┌─────────────────┐</span></span>
<span class="line"><span>│   发起请求       │</span></span>
<span class="line"><span>└────────┬────────┘</span></span>
<span class="line"><span>         │</span></span>
<span class="line"><span>         ▼</span></span>
<span class="line"><span>┌─────────────────┐</span></span>
<span class="line"><span>│  检查本地缓存    │</span></span>
<span class="line"><span>└────────┬────────┘</span></span>
<span class="line"><span>         │</span></span>
<span class="line"><span>    ┌────┴────┐</span></span>
<span class="line"><span>    │         │</span></span>
<span class="line"><span>    ▼         ▼</span></span>
<span class="line"><span>┌────────┐ ┌────────┐</span></span>
<span class="line"><span>│ 命中    │ │ 未命中 │</span></span>
<span class="line"><span>└───┬────┘ └───┬────┘</span></span>
<span class="line"><span>    │          │</span></span>
<span class="line"><span>    ▼          ▼</span></span>
<span class="line"><span>┌────────┐ ┌──────────┐</span></span>
<span class="line"><span>│检查TTL │ │ 发起网络请求│</span></span>
<span class="line"><span>└───┬────┘ └────┬─────┘</span></span>
<span class="line"><span>    │            │</span></span>
<span class="line"><span>    ▼            ▼</span></span>
<span class="line"><span>┌────────┐  ┌────────┐</span></span>
<span class="line"><span>│ 有效   │  │ 成功   │</span></span>
<span class="line"><span>└───┬────┘  └────┬───┘</span></span>
<span class="line"><span>    │            │</span></span>
<span class="line"><span>    └────┬───────┘</span></span>
<span class="line"><span>         ▼</span></span>
<span class="line"><span>    ┌────────┐</span></span>
<span class="line"><span>    │ 渲染徽章│</span></span>
<span class="line"><span>    └────────┘</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br><span class="line-number">25</span><br><span class="line-number">26</span><br><span class="line-number">27</span><br><span class="line-number">28</span><br><span class="line-number">29</span><br><span class="line-number">30</span><br><span class="line-number">31</span><br></div></div><h2 id="基础配置" tabindex="-1">基础配置 <a class="header-anchor" href="#基础配置" aria-label="Permalink to &quot;基础配置&quot;">​</a></h2><h3 id="启用缓存" tabindex="-1">启用缓存 <a class="header-anchor" href="#启用缓存" aria-label="Permalink to &quot;启用缓存&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  cache: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h3 id="设置缓存时间" tabindex="-1">设置缓存时间 <a class="header-anchor" href="#设置缓存时间" aria-label="Permalink to &quot;设置缓存时间&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  cache: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    ttlMs: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">30</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> // 30 分钟</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h3 id="禁用缓存" tabindex="-1">禁用缓存 <a class="header-anchor" href="#禁用缓存" aria-label="Permalink to &quot;禁用缓存&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  cache: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">false</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br></div></div><h2 id="环境配置" tabindex="-1">环境配置 <a class="header-anchor" href="#环境配置" aria-label="Permalink to &quot;环境配置&quot;">​</a></h2><h3 id="开发环境" tabindex="-1">开发环境 <a class="header-anchor" href="#开发环境" aria-label="Permalink to &quot;开发环境&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> devCacheConfig</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  ttlMs: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">1</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> // 1 分钟，便于调试</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="生产环境" tabindex="-1">生产环境 <a class="header-anchor" href="#生产环境" aria-label="Permalink to &quot;生产环境&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> prodCacheConfig</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  ttlMs: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> // 1 小时，提升性能</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h2 id="缓存键" tabindex="-1">缓存键 <a class="header-anchor" href="#缓存键" aria-label="Permalink to &quot;缓存键&quot;">​</a></h2><h3 id="键的生成规则" tabindex="-1">键的生成规则 <a class="header-anchor" href="#键的生成规则" aria-label="Permalink to &quot;键的生成规则&quot;">​</a></h3><p>缓存键基于配置 URL 生成：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> cacheKey</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> buildCacheKey</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 结果: &#39;link-exchange:https://cdn.example.com/badges.json&#39;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h3 id="版本化缓存" tabindex="-1">版本化缓存 <a class="header-anchor" href="#版本化缓存" aria-label="Permalink to &quot;版本化缓存&quot;">​</a></h3><p>通过修改 URL 实现版本控制：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 版本 1</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">source</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.v1.json&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 版本 2</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">source</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.v2.json&#39;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h2 id="缓存事件" tabindex="-1">缓存事件 <a class="header-anchor" href="#缓存事件" aria-label="Permalink to &quot;缓存事件&quot;">​</a></h2><h3 id="cache-hit" tabindex="-1">cache_hit <a class="header-anchor" href="#cache-hit" aria-label="Permalink to &quot;cache_hit&quot;">​</a></h3><p>缓存命中时触发：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  telemetry: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (event.type </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;cache_hit&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;使用缓存:&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, event.configVersion)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h3 id="cache-miss" tabindex="-1">cache_miss <a class="header-anchor" href="#cache-miss" aria-label="Permalink to &quot;cache_miss&quot;">​</a></h3><p>缓存未命中时触发：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  telemetry: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (event.type </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;cache_miss&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;缓存未命中，发起网络请求&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h3 id="cache-stale-used" tabindex="-1">cache_stale_used <a class="header-anchor" href="#cache-stale-used" aria-label="Permalink to &quot;cache_stale_used&quot;">​</a></h3><p>使用过期缓存时触发：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  telemetry: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (event.type </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;cache_stale_used&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;网络失败，使用过期缓存:&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, event.configVersion)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h2 id="手动缓存管理" tabindex="-1">手动缓存管理 <a class="header-anchor" href="#手动缓存管理" aria-label="Permalink to &quot;手动缓存管理&quot;">​</a></h2><h3 id="读取缓存" tabindex="-1">读取缓存 <a class="header-anchor" href="#读取缓存" aria-label="Permalink to &quot;读取缓存&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { readCache, buildCacheKey } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/core&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> key</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> buildCacheKey</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> cached</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> readCache</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(key)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (cached) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;缓存版本:&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, cached.configVersion)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;缓存时间:&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">new</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Date</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(cached.cachedAt))</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><h3 id="写入缓存" tabindex="-1">写入缓存 <a class="header-anchor" href="#写入缓存" aria-label="Permalink to &quot;写入缓存&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { writeCache, buildCacheKey } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/core&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> key</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> buildCacheKey</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">writeCache</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(key, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  cachedAt: Date.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">now</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  configVersion: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;2&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  data: config</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br></div></div><h3 id="清除缓存" tabindex="-1">清除缓存 <a class="header-anchor" href="#清除缓存" aria-label="Permalink to &quot;清除缓存&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { clearCache, buildCacheKey } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/core&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> key</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> buildCacheKey</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">clearCache</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(key)</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="检查缓存有效性" tabindex="-1">检查缓存有效性 <a class="header-anchor" href="#检查缓存有效性" aria-label="Permalink to &quot;检查缓存有效性&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { isCacheValid, readCache, buildCacheKey } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/core&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> key</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> buildCacheKey</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> cached</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> readCache</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(key)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (cached </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">&amp;&amp;</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> isCacheValid</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(cached, </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">30</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;缓存有效&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">} </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">else</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;缓存无效或过期&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><h2 id="高级用法" tabindex="-1">高级用法 <a class="header-anchor" href="#高级用法" aria-label="Permalink to &quot;高级用法&quot;">​</a></h2><h3 id="自定义缓存存储" tabindex="-1">自定义缓存存储 <a class="header-anchor" href="#自定义缓存存储" aria-label="Permalink to &quot;自定义缓存存储&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">class</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> CustomCacheStorage</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  constructor</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">    this</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">.cache </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> new</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Map</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">()</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  getItem</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">key</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> item</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> this</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">.cache.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">get</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(key)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (item) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      return</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> JSON</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">stringify</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(item)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> null</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  setItem</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">key</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">value</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">    this</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">.cache.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">set</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(key, </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">JSON</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">parse</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(value))</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  removeItem</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">key</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">    this</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">.cache.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">delete</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(key)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> customStorage</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> new</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> CustomCacheStorage</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">()</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br></div></div><h3 id="缓存预热" tabindex="-1">缓存预热 <a class="header-anchor" href="#缓存预热" aria-label="Permalink to &quot;缓存预热&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 页面加载时预热缓存</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">async</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> warmupCache</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  try</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> response</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> await</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> fetch</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> config</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> await</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> response.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">json</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> key</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> buildCacheKey</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    writeCache</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(key, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      cachedAt: Date.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">now</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      configVersion: config.configVersion,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      data: config</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    })</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;缓存预热完成&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">catch</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (error) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">error</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;缓存预热失败:&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, error)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br></div></div><h3 id="条件缓存" tabindex="-1">条件缓存 <a class="header-anchor" href="#条件缓存" aria-label="Permalink to &quot;条件缓存&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> shouldUseCache</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  // 仅在快速网络时使用缓存</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> connection</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> navigator.connection </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">||</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> navigator.mozConnection </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">||</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> navigator.webkitConnection</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (connection) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> connection.effectiveType </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">!==</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;slow-2g&#39;</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> &amp;&amp;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> connection.effectiveType </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">!==</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;2g&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> true</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  cache: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">shouldUseCache</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    ttlMs: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">30</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br></div></div><h2 id="性能优化" tabindex="-1">性能优化 <a class="header-anchor" href="#性能优化" aria-label="Permalink to &quot;性能优化&quot;">​</a></h2><h3 id="service-worker-缓存" tabindex="-1">Service Worker 缓存 <a class="header-anchor" href="#service-worker-缓存" aria-label="Permalink to &quot;Service Worker 缓存&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// service-worker.js</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">self.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">addEventListener</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;fetch&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (event.request.url.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">includes</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    event.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">respondWith</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      caches.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">match</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(event.request).</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">then</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">((</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">response</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">        return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> response </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">||</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> fetch</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(event.request)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    )</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><h3 id="预缓存配置" tabindex="-1">预缓存配置 <a class="header-anchor" href="#预缓存配置" aria-label="Permalink to &quot;预缓存配置&quot;">​</a></h3><div class="language-html line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">html</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">link</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> rel</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;preload&quot;</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> href</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://cdn.example.com/badges.json&quot;</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> as</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;fetch&quot;</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> crossorigin</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="缓存统计" tabindex="-1">缓存统计 <a class="header-anchor" href="#缓存统计" aria-label="Permalink to &quot;缓存统计&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">let</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> cacheHits </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 0</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">let</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> cacheMisses </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 0</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  telemetry: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (event.type </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;cache_hit&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        cacheHits</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">++</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">else</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (event.type </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;cache_miss&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        cacheMisses</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">++</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      }</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> hitRate</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> cacheHits </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">/</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (cacheHits </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">+</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> cacheMisses) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">*</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 100</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">\`缓存命中率: \${</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">hitRate</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">toFixed</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">(</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">2</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">)</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">}%\`</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br></div></div><h2 id="故障处理" tabindex="-1">故障处理 <a class="header-anchor" href="#故障处理" aria-label="Permalink to &quot;故障处理&quot;">​</a></h2><h3 id="缓存损坏" tabindex="-1">缓存损坏 <a class="header-anchor" href="#缓存损坏" aria-label="Permalink to &quot;缓存损坏&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">try</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> cached</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> readCache</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(key)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (cached) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">    // 验证缓存数据</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">!</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">cached.data </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">||</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> !</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">cached.configVersion) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      throw</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> new</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Error</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;Invalid cache data&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">} </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">catch</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (error) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">error</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;缓存损坏，清除缓存:&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, error)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  clearCache</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(key)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><h3 id="存储空间不足" tabindex="-1">存储空间不足 <a class="header-anchor" href="#存储空间不足" aria-label="Permalink to &quot;存储空间不足&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> checkStorageAvailability</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  try</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> testKey</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;__storage_test__&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    localStorage.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">setItem</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(testKey, </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;test&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    localStorage.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">removeItem</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(testKey)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> true</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">catch</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (error) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (error </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">instanceof</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> DOMException</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> &amp;&amp;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      error.name </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;QuotaExceededError&#39;</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> ||</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      error.name </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">===</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;NS_ERROR_DOM_QUOTA_REACHED&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    )) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">error</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;存储空间不足&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      return</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> false</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">    return</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> true</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><h2 id="最佳实践" tabindex="-1">最佳实践 <a class="header-anchor" href="#最佳实践" aria-label="Permalink to &quot;最佳实践&quot;">​</a></h2><h3 id="_1-合理设置-ttl" tabindex="-1">1. 合理设置 TTL <a class="header-anchor" href="#_1-合理设置-ttl" aria-label="Permalink to &quot;1. 合理设置 TTL&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 根据配置更新频率设置 TTL</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> cacheTTL</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  // 频繁更新的配置</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  frequent: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">5</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,     </span><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 5 分钟</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  // 正常更新频率</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  normal: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">30</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,      </span><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 30 分钟</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">  // 很少更新的配置</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  rare: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#6A737D" })}">         // 1 小时</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h3 id="_2-版本管理" tabindex="-1">2. 版本管理 <a class="header-anchor" href="#_2-版本管理" aria-label="Permalink to &quot;2. 版本管理&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 使用查询参数实现版本控制</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">source</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json?v=2&#39;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br></div></div><h3 id="_3-监控缓存性能" tabindex="-1">3. 监控缓存性能 <a class="header-anchor" href="#_3-监控缓存性能" aria-label="Permalink to &quot;3. 监控缓存性能&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  telemetry: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">      // 发送缓存指标到监控平台</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">      if</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> ([</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;cache_hit&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;cache_miss&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;cache_stale_used&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">].</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">includes</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(event.type)) {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        analytics.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">track</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;cache_event&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          type: event.type,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          configVersion: event.configVersion</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><h3 id="_4-降级策略" tabindex="-1">4. 降级策略 <a class="header-anchor" href="#_4-降级策略" aria-label="Permalink to &quot;4. 降级策略&quot;">​</a></h3><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  cache: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    ttlMs: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">30</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  },</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  fallback: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    snapshot: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">      // 离线时使用的快照配置</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      configVersion: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;1&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      schemaVersion: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;1.0.0&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      updatedAt: </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">new</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Date</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">().</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">toISOString</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(),</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      badges: [</span><span style="${ssrRenderStyle({ "color": "#6A737D" })}">/* ... */</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br></div></div><h2 id="常见问题" tabindex="-1">常见问题 <a class="header-anchor" href="#常见问题" aria-label="Permalink to &quot;常见问题&quot;">​</a></h2><h3 id="q-缓存存储在哪里" tabindex="-1">Q: 缓存存储在哪里？ <a class="header-anchor" href="#q-缓存存储在哪里" aria-label="Permalink to &quot;Q: 缓存存储在哪里？&quot;">​</a></h3><p>A: 使用浏览器的 localStorage，键名为 <code>link-exchange:\${url}</code>。</p><h3 id="q-缓存会占用多少空间" tabindex="-1">Q: 缓存会占用多少空间？ <a class="header-anchor" href="#q-缓存会占用多少空间" aria-label="Permalink to &quot;Q: 缓存会占用多少空间？&quot;">​</a></h3><p>A: 取决于配置大小，通常在几 KB 到几十 KB 之间。</p><h3 id="q-如何清除所有缓存" tabindex="-1">Q: 如何清除所有缓存？ <a class="header-anchor" href="#q-如何清除所有缓存" aria-label="Permalink to &quot;Q: 如何清除所有缓存？&quot;">​</a></h3><p>A: 遍历 localStorage 并删除所有 <code>link-exchange:</code> 开头的键。</p><h3 id="q-缓存失败会怎样" tabindex="-1">Q: 缓存失败会怎样？ <a class="header-anchor" href="#q-缓存失败会怎样" aria-label="Permalink to &quot;Q: 缓存失败会怎样？&quot;">​</a></h3><p>A: SDK 会尝试从网络获取配置，网络也失败时使用快照配置。</p><h2 id="下一步" tabindex="-1">下一步 <a class="header-anchor" href="#下一步" aria-label="Permalink to &quot;下一步&quot;">​</a></h2><ul><li><a href="/LinkExchangeBadges/guide/configuration.html">配置选项</a></li><li><a href="/LinkExchangeBadges/guide/badge-rules.html">徽章规则</a></li><li><a href="/LinkExchangeBadges/api/core.html">API 参考</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("docs/guide/caching.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const caching = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  caching as default
};
