import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"","description":"","frontmatter":{"layout":"home","hero":{"name":"Link Exchange Badges","text":"跨栈徽章展示 SDK","tagline":"在任何 Web 应用中轻松展示合作伙伴徽章","actions":[{"theme":"brand","text":"快速开始","link":"/guide/getting-started"},{"theme":"alt","text":"查看 API","link":"/api/core"},{"theme":"alt","text":"GitHub","link":"https://github.com/yourusername/link-exchange-badges"}]},"features":[{"icon":"⚡️","title":"极简集成","details":"只需几行代码，即可在 HTML、React、Next.js 等任何框架中集成徽章展示功能。"},{"icon":"🎯","title":"类型安全","details":"完整的 TypeScript 支持，提供准确的类型定义和智能提示。"},{"icon":"🔄","title":"远程配置","details":"通过远程 JSON 配置动态控制徽章展示，无需重新部署应用。"},{"icon":"🛡️","title":"安全可靠","details":"内置安全白名单、配置验证和错误处理，确保生产环境稳定运行。"},{"icon":"📊","title":"遥测分析","details":"内置事件追踪系统，可集成任意分析平台监控徽章性能。"},{"icon":"💾","title":"智能缓存","details":"自动缓存远程配置，减少网络请求，提升加载性能。"}]},"headers":[],"relativePath":"docs/index.md","filePath":"docs/index.md"}');
const _sfc_main = { name: "docs/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h2 id="快速预览" tabindex="-1">快速预览 <a class="header-anchor" href="#快速预览" aria-label="Permalink to &quot;快速预览&quot;">​</a></h2><h3 id="html-使用" tabindex="-1">HTML 使用 <a class="header-anchor" href="#html-使用" aria-label="Permalink to &quot;HTML 使用&quot;">​</a></h3><div class="language-html line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">html</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">&lt;!-- 引入 SDK --&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">script</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> src</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://cdn.example.com/link-exchange.js&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">script</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">&lt;!-- 挂载徽章 --&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">footer</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> id</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;badges&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">footer</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">script</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">script</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h3 id="react-使用" tabindex="-1">React 使用 <a class="header-anchor" href="#react-使用" aria-label="Permalink to &quot;React 使用&quot;">​</a></h3><div class="language-jsx line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">jsx</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { LinkExchange } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/react&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Footer</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">LinkExchange</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">      source</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://cdn.example.com/badges.json&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">      siteId</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;my-site&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">      environment</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;production&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  )</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h2 id="核心特性" tabindex="-1">核心特性 <a class="header-anchor" href="#核心特性" aria-label="Permalink to &quot;核心特性&quot;">​</a></h2><h3 id="🎨-灵活的渲染系统" tabindex="-1">🎨 灵活的渲染系统 <a class="header-anchor" href="#🎨-灵活的渲染系统" aria-label="Permalink to &quot;🎨 灵活的渲染系统&quot;">​</a></h3><p>支持图片徽章，未来将扩展 HTML、SVG 等多种渲染类型。每个徽章可配置：</p><ul><li>自定义尺寸和样式</li><li>链接目标和关系属性</li><li>显示规则（站点、环境、语言）</li></ul><h3 id="🌐-多环境支持" tabindex="-1">🌐 多环境支持 <a class="header-anchor" href="#🌐-多环境支持" aria-label="Permalink to &quot;🌐 多环境支持&quot;">​</a></h3><p>通过 <code>environment</code> 参数控制不同环境的徽章展示：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  environment: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;production&#39;</span><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> // development | staging | production</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="🔒-安全白名单" tabindex="-1">🔒 安全白名单 <a class="header-anchor" href="#🔒-安全白名单" aria-label="Permalink to &quot;🔒 安全白名单&quot;">​</a></h3><p>生产环境推荐配置域名白名单，防止配置被篡改：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  security: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    allowedLinkDomains: [</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;github.com&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;npmjs.com&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    allowedImageDomains: [</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;img.shields.io&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;github.com&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h3 id="📡-内置遥测" tabindex="-1">📡 内置遥测 <a class="header-anchor" href="#📡-内置遥测" aria-label="Permalink to &quot;📡 内置遥测&quot;">​</a></h3><p>追踪所有关键事件，集成监控平台：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  telemetry: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">      // 发送到你的分析平台</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      analytics.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">track</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(event.type, event)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><h2 id="为什么选择-link-exchange-badges" tabindex="-1">为什么选择 Link Exchange Badges？ <a class="header-anchor" href="#为什么选择-link-exchange-badges" aria-label="Permalink to &quot;为什么选择 Link Exchange Badges？&quot;">​</a></h2><h3 id="传统方式的痛点" tabindex="-1">传统方式的痛点 <a class="header-anchor" href="#传统方式的痛点" aria-label="Permalink to &quot;传统方式的痛点&quot;">​</a></h3><ol><li><strong>硬编码徽章</strong>：每次更新都需要重新部署应用</li><li><strong>缺乏灵活性</strong>：无法根据环境动态调整徽章</li><li><strong>类型不安全</strong>：配置错误只能在运行时发现</li><li><strong>缺少监控</strong>：无法追踪徽章展示和点击数据</li></ol><h3 id="我们的解决方案" tabindex="-1">我们的解决方案 <a class="header-anchor" href="#我们的解决方案" aria-label="Permalink to &quot;我们的解决方案&quot;">​</a></h3><ol><li><strong>远程配置</strong>：通过 JSON 配置实时更新徽章</li><li><strong>规则引擎</strong>：支持站点、环境、语言等多维度规则</li><li><strong>类型安全</strong>：完整的 TypeScript 类型定义</li><li><strong>事件追踪</strong>：内置遥测系统，集成任意分析平台</li></ol><h2 id="下一步" tabindex="-1">下一步 <a class="header-anchor" href="#下一步" aria-label="Permalink to &quot;下一步&quot;">​</a></h2><ul><li><a href="/LinkExchangeBadges/guide/getting-started.html">阅读快速开始指南</a></li><li><a href="/LinkExchangeBadges/api/core.html">查看 API 参考</a></li><li><a href="/LinkExchangeBadges/examples/html.html">浏览完整示例</a></li><li><a href="/LinkExchangeBadges/advanced/best-practices.html">了解最佳实践</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("docs/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
