import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"介绍","description":"","frontmatter":{},"headers":[],"relativePath":"docs/guide/introduction.md","filePath":"docs/guide/introduction.md"}');
const _sfc_main = { name: "docs/guide/introduction.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="介绍" tabindex="-1">介绍 <a class="header-anchor" href="#介绍" aria-label="Permalink to &quot;介绍&quot;">​</a></h1><p>Link Exchange Badges 是一个跨栈的徽章展示 SDK，让你能够在任何 Web 应用中轻松展示合作伙伴徽章。</p><h2 id="什么是-link-exchange-badges" tabindex="-1">什么是 Link Exchange Badges？ <a class="header-anchor" href="#什么是-link-exchange-badges" aria-label="Permalink to &quot;什么是 Link Exchange Badges？&quot;">​</a></h2><p>Link Exchange Badges 是一个轻量级、类型安全的 JavaScript SDK，用于在 Web 应用中动态展示徽章。它支持：</p><ul><li><strong>多框架支持</strong>：原生 HTML、React、Next.js 等</li><li><strong>远程配置</strong>：通过 JSON 配置动态控制徽章</li><li><strong>规则引擎</strong>：支持站点、环境、语言等多维度规则</li><li><strong>类型安全</strong>：完整的 TypeScript 类型定义</li><li><strong>遥测追踪</strong>：内置事件追踪系统</li></ul><h2 id="设计理念" tabindex="-1">设计理念 <a class="header-anchor" href="#设计理念" aria-label="Permalink to &quot;设计理念&quot;">​</a></h2><h3 id="_1-简单优先" tabindex="-1">1. 简单优先 <a class="header-anchor" href="#_1-简单优先" aria-label="Permalink to &quot;1. 简单优先&quot;">​</a></h3><p>API 设计遵循&quot;约定优于配置&quot;的原则，最小可用配置只需一行代码：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h3 id="_2-类型安全" tabindex="-1">2. 类型安全 <a class="header-anchor" href="#_2-类型安全" aria-label="Permalink to &quot;2. 类型安全&quot;">​</a></h3><p>使用 Zod 进行运行时验证，TypeScript 提供编译时检查：</p><div class="language-typescript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> type</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { BadgeConfig, MountOptions } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/core&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> options</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">:</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> MountOptions</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  siteId: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;my-site&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  environment: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;production&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h3 id="_3-渐进增强" tabindex="-1">3. 渐进增强 <a class="header-anchor" href="#_3-渐进增强" aria-label="Permalink to &quot;3. 渐进增强&quot;">​</a></h3><p>从简单用例开始，逐步使用高级功能：</p><ul><li><strong>基础</strong>：远程配置 + 缓存</li><li><strong>进阶</strong>：规则引擎 + 安全白名单</li><li><strong>高级</strong>：遥测追踪 + 自定义渲染</li></ul><h3 id="_4-错误容忍" tabindex="-1">4. 错误容忍 <a class="header-anchor" href="#_4-错误容忍" aria-label="Permalink to &quot;4. 错误容忍&quot;">​</a></h3><p>SDK 内置完善的错误处理机制：</p><ul><li>远程配置失败时使用缓存</li><li>缓存过期时仍可作为 fallback</li><li>所有错误都可静默处理，不影响主应用</li></ul><h2 id="架构概览" tabindex="-1">架构概览 <a class="header-anchor" href="#架构概览" aria-label="Permalink to &quot;架构概览&quot;">​</a></h2><div class="language- line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span>┌─────────────────┐</span></span>
<span class="line"><span>│   Web 应用      │</span></span>
<span class="line"><span>└────────┬────────┘</span></span>
<span class="line"><span>         │</span></span>
<span class="line"><span>         ▼</span></span>
<span class="line"><span>┌─────────────────┐</span></span>
<span class="line"><span>│  Link Exchange  │</span></span>
<span class="line"><span>│     SDK         │</span></span>
<span class="line"><span>└────────┬────────┘</span></span>
<span class="line"><span>         │</span></span>
<span class="line"><span>    ┌────┴────┐</span></span>
<span class="line"><span>    │         │</span></span>
<span class="line"><span>    ▼         ▼</span></span>
<span class="line"><span>┌────────┐ ┌──────────┐</span></span>
<span class="line"><span>│ 远程   │ │ 本地缓存 │</span></span>
<span class="line"><span>│ 配置   │ │          │</span></span>
<span class="line"><span>└────────┘ └──────────┘</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br></div></div><h2 id="核心概念" tabindex="-1">核心概念 <a class="header-anchor" href="#核心概念" aria-label="Permalink to &quot;核心概念&quot;">​</a></h2><h3 id="_1-配置-badgeconfig" tabindex="-1">1. 配置 (BadgeConfig) <a class="header-anchor" href="#_1-配置-badgeconfig" aria-label="Permalink to &quot;1. 配置 (BadgeConfig)&quot;">​</a></h3><p>远程配置对象，包含所有徽章的定义和元数据：</p><div class="language-json line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  &quot;configVersion&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;1&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  &quot;schemaVersion&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;1.0.0&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  &quot;updatedAt&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;2024-01-01T00:00:00Z&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  &quot;badges&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;id&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;github&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;name&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;GitHub&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;enabled&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;renderType&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;image&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;imageUrl&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://img.shields.io/badge/GitHub-100000?logo=github&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;linkUrl&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://github.com&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  ]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><h3 id="_2-挂载选项-mountoptions" tabindex="-1">2. 挂载选项 (MountOptions) <a class="header-anchor" href="#_2-挂载选项-mountoptions" aria-label="Permalink to &quot;2. 挂载选项 (MountOptions)&quot;">​</a></h3><p>SDK 的配置选项，控制徽章的获取和渲染行为：</p><div class="language-typescript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">typescript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">  source</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: string                    </span><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 远程配置 URL</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  siteId</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> string                   </span><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 站点标识</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  group</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> string                    </span><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 徽章分组</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  environment</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;development&#39;</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> |</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;staging&#39;</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> |</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;production&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  locale</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> string                   </span><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// 语言标识</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  cache</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { enabled?: boolean; ttlMs</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> number }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  security</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { allowedLinkDomains?: string[] }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  telemetry</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { enabled?: boolean; onEvent</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">?:</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> void</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br></div></div><h3 id="_3-规则引擎" tabindex="-1">3. 规则引擎 <a class="header-anchor" href="#_3-规则引擎" aria-label="Permalink to &quot;3. 规则引擎&quot;">​</a></h3><p>根据规则过滤徽章：</p><ul><li><strong>siteIds</strong>：只在指定站点展示</li><li><strong>environments</strong>：只在指定环境展示</li><li><strong>locales</strong>：只在指定语言展示</li></ul><h3 id="_4-遥测事件" tabindex="-1">4. 遥测事件 <a class="header-anchor" href="#_4-遥测事件" aria-label="Permalink to &quot;4. 遥测事件&quot;">​</a></h3><p>SDK 生命周期中的关键事件：</p><ul><li><code>config_fetch_start</code>：开始获取配置</li><li><code>config_fetch_success</code>：配置获取成功</li><li><code>cache_hit</code>：缓存命中</li><li><code>render_success</code>：渲染成功</li><li><code>badge_click</code>：徽章点击</li></ul><h2 id="适用场景" tabindex="-1">适用场景 <a class="header-anchor" href="#适用场景" aria-label="Permalink to &quot;适用场景&quot;">​</a></h2><h3 id="_1-合作伙伴展示" tabindex="-1">1. 合作伙伴展示 <a class="header-anchor" href="#_1-合作伙伴展示" aria-label="Permalink to &quot;1. 合作伙伴展示&quot;">​</a></h3><p>在官网底部展示合作伙伴的 Logo 和链接：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#partners&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/partners.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  group: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;partners&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="_2-技术栈展示" tabindex="-1">2. 技术栈展示 <a class="header-anchor" href="#_2-技术栈展示" aria-label="Permalink to &quot;2. 技术栈展示&quot;">​</a></h3><p>展示项目使用的技术栈：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#tech-stack&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/tech-stack.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  group: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;technologies&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="_3-认证徽章" tabindex="-1">3. 认证徽章 <a class="header-anchor" href="#_3-认证徽章" aria-label="Permalink to &quot;3. 认证徽章&quot;">​</a></h3><p>展示认证、奖项等徽章：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#certifications&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/certifications.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  environment: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;production&#39;</span><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> // 只在生产环境展示</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h2 id="技术栈" tabindex="-1">技术栈 <a class="header-anchor" href="#技术栈" aria-label="Permalink to &quot;技术栈&quot;">​</a></h2><ul><li><strong>语言</strong>：TypeScript 5.0+</li><li><strong>构建</strong>：tsup</li><li><strong>验证</strong>：Zod</li><li><strong>测试</strong>：Vitest</li><li><strong>文档</strong>：VitePress</li></ul><h2 id="浏览器支持" tabindex="-1">浏览器支持 <a class="header-anchor" href="#浏览器支持" aria-label="Permalink to &quot;浏览器支持&quot;">​</a></h2><ul><li>Chrome/Edge 90+</li><li>Firefox 88+</li><li>Safari 14+</li></ul><h2 id="许可证" tabindex="-1">许可证 <a class="header-anchor" href="#许可证" aria-label="Permalink to &quot;许可证&quot;">​</a></h2><p>MIT License - 详见 <a href="https://github.com/yourusername/link-exchange-badges/blob/main/LICENSE" target="_blank" rel="noreferrer">LICENSE</a></p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("docs/guide/introduction.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const introduction = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  introduction as default
};
