import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"快速开始","description":"","frontmatter":{},"headers":[],"relativePath":"guide/getting-started.md","filePath":"guide/getting-started.md"}');
const _sfc_main = { name: "guide/getting-started.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="快速开始" tabindex="-1">快速开始 <a class="header-anchor" href="#快速开始" aria-label="Permalink to &quot;快速开始&quot;">​</a></h1><p>本指南将帮助你在 5 分钟内集成 Link Exchange Badges SDK。</p><h2 id="选择你的集成方式" tabindex="-1">选择你的集成方式 <a class="header-anchor" href="#选择你的集成方式" aria-label="Permalink to &quot;选择你的集成方式&quot;">​</a></h2><p>根据你的技术栈选择合适的集成方式：</p><ul><li><strong>HTML</strong>：使用 CDN 脚本，无需构建工具</li><li><strong>React</strong>：使用 React 组件，适合 React 应用</li><li><strong>Next.js</strong>：使用 React 组件，支持 SSR</li><li><strong>其他框架</strong>：使用核心 API 或 CDN 脚本</li></ul><h2 id="html-集成" tabindex="-1">HTML 集成 <a class="header-anchor" href="#html-集成" aria-label="Permalink to &quot;HTML 集成&quot;">​</a></h2><h3 id="_1-引入-sdk" tabindex="-1">1. 引入 SDK <a class="header-anchor" href="#_1-引入-sdk" aria-label="Permalink to &quot;1. 引入 SDK&quot;">​</a></h3><p>在 HTML 中添加 script 标签：</p><div class="language-html line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">html</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;!</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">DOCTYPE</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> html</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">html</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">head</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">script</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> src</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://cdn.example.com/link-exchange.js&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">script</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">head</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">body</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">footer</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> id</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;badges&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">footer</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">script</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    })</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  &lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">script</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">body</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">html</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><h3 id="_2-创建配置文件" tabindex="-1">2. 创建配置文件 <a class="header-anchor" href="#_2-创建配置文件" aria-label="Permalink to &quot;2. 创建配置文件&quot;">​</a></h3><p>创建 <code>badges.json</code>：</p><div class="language-json line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">json</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  &quot;configVersion&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;1&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  &quot;schemaVersion&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;1.0.0&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  &quot;updatedAt&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;2024-01-01T00:00:00Z&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">  &quot;badges&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: [</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;id&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;github&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;name&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;GitHub&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;enabled&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;renderType&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;image&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;imageUrl&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://img.shields.io/badge/GitHub-100000?logo=github&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">      &quot;linkUrl&quot;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://github.com&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  ]</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br></div></div><h3 id="_3-运行" tabindex="-1">3. 运行 <a class="header-anchor" href="#_3-运行" aria-label="Permalink to &quot;3. 运行&quot;">​</a></h3><p>将 <code>badges.json</code> 部署到 CDN，然后在浏览器中打开 HTML 文件。</p><h2 id="react-集成" tabindex="-1">React 集成 <a class="header-anchor" href="#react-集成" aria-label="Permalink to &quot;React 集成&quot;">​</a></h2><h3 id="_1-安装包" tabindex="-1">1. 安装包 <a class="header-anchor" href="#_1-安装包" aria-label="Permalink to &quot;1. 安装包&quot;">​</a></h3><div class="language-bash line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> install</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> @link-exchange/react</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"># 或</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">pnpm</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> add</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> @link-exchange/react</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}"># 或</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">yarn</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> add</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> @link-exchange/react</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br></div></div><h3 id="_2-使用组件" tabindex="-1">2. 使用组件 <a class="header-anchor" href="#_2-使用组件" aria-label="Permalink to &quot;2. 使用组件&quot;">​</a></h3><div class="language-jsx line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">jsx</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { LinkExchange } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/react&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> App</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">div</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">h1</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;我的网站&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">h1</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      &lt;</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">LinkExchange</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">        source</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://cdn.example.com/badges.json&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    &lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">div</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  )</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br></div></div><h3 id="_3-高级用法" tabindex="-1">3. 高级用法 <a class="header-anchor" href="#_3-高级用法" aria-label="Permalink to &quot;3. 高级用法&quot;">​</a></h3><div class="language-jsx line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">jsx</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { LinkExchange } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/react&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Footer</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">footer</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      &lt;</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">LinkExchange</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">        source</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;https://cdn.example.com/badges.json&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">        siteId</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;my-website&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">        environment</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;production&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">        locale</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;zh-CN&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">        cache</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          ttlMs: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">30</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 60</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> *</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}"> 1000</span><span style="${ssrRenderStyle({ "color": "#6A737D" })}"> // 30 分钟</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        }}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">        telemetry</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">          onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">            console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;Badge event:&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, event)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">          }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">        }}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    &lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">footer</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  )</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br><span class="line-number">15</span><br><span class="line-number">16</span><br><span class="line-number">17</span><br><span class="line-number">18</span><br><span class="line-number">19</span><br><span class="line-number">20</span><br><span class="line-number">21</span><br><span class="line-number">22</span><br><span class="line-number">23</span><br><span class="line-number">24</span><br></div></div><h2 id="next-js-集成" tabindex="-1">Next.js 集成 <a class="header-anchor" href="#next-js-集成" aria-label="Permalink to &quot;Next.js 集成&quot;">​</a></h2><h3 id="_1-安装包-1" tabindex="-1">1. 安装包 <a class="header-anchor" href="#_1-安装包-1" aria-label="Permalink to &quot;1. 安装包&quot;">​</a></h3><div class="language-bash line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> install</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> @link-exchange/react</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><h3 id="_2-创建客户端组件" tabindex="-1">2. 创建客户端组件 <a class="header-anchor" href="#_2-创建客户端组件" aria-label="Permalink to &quot;2. 创建客户端组件&quot;">​</a></h3><p>由于 SDK 需要访问浏览器 API，需要使用 <code>&#39;use client&#39;</code>：</p><div class="language-jsx line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">jsx</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// components/Badges.tsx</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;use client&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { LinkExchange } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@link-exchange/react&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">export</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Badges</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">LinkExchange</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">      source</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{process.env.</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">NEXT_PUBLIC_BADGES_URL</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">      siteId</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&quot;my-nextjs-app&quot;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">      environment</span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">{process.env.</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">NODE_ENV</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  )</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br><span class="line-number">12</span><br><span class="line-number">13</span><br><span class="line-number">14</span><br></div></div><h3 id="_3-在页面中使用" tabindex="-1">3. 在页面中使用 <a class="header-anchor" href="#_3-在页面中使用" aria-label="Permalink to &quot;3. 在页面中使用&quot;">​</a></h3><div class="language-jsx line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">jsx</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#6A737D" })}">// app/page.tsx</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> { Badges } </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}"> &#39;@/components/Badges&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">export</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> default</span><span style="${ssrRenderStyle({ "color": "#F97583" })}"> function</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}"> Home</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> (</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">main</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      &lt;</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">h1</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;我的 Next.js 应用&lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">h1</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">      &lt;</span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">Badges</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> /&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    &lt;/</span><span style="${ssrRenderStyle({ "color": "#85E89D" })}">main</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  )</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">}</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br><span class="line-number">8</span><br><span class="line-number">9</span><br><span class="line-number">10</span><br><span class="line-number">11</span><br></div></div><h3 id="_4-环境变量" tabindex="-1">4. 环境变量 <a class="header-anchor" href="#_4-环境变量" aria-label="Permalink to &quot;4. 环境变量&quot;">​</a></h3><p>在 <code>.env.local</code> 中配置：</p><div class="language-env line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">env</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span>NEXT_PUBLIC_BADGES_URL=https://cdn.example.com/badges.json</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br></div></div><h2 id="验证集成" tabindex="-1">验证集成 <a class="header-anchor" href="#验证集成" aria-label="Permalink to &quot;验证集成&quot;">​</a></h2><h3 id="_1-检查控制台" tabindex="-1">1. 检查控制台 <a class="header-anchor" href="#_1-检查控制台" aria-label="Permalink to &quot;1. 检查控制台&quot;">​</a></h3><p>打开浏览器控制台，你应该看到：</p><div class="language- line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span>[LinkExchange] SDK initialized</span></span>
<span class="line"><span>[LinkExchange] Fetching config: https://cdn.example.com/badges.json</span></span>
<span class="line"><span>[LinkExchange] Config fetched successfully</span></span>
<span class="line"><span>[LinkExchange] Rendering 1 badge(s)</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br></div></div><h3 id="_2-检查渲染结果" tabindex="-1">2. 检查渲染结果 <a class="header-anchor" href="#_2-检查渲染结果" aria-label="Permalink to &quot;2. 检查渲染结果&quot;">​</a></h3><p>在页面上应该能看到徽章显示。</p><h3 id="_3-测试交互" tabindex="-1">3. 测试交互 <a class="header-anchor" href="#_3-测试交互" aria-label="Permalink to &quot;3. 测试交互&quot;">​</a></h3><p>点击徽章，应该能跳转到配置的链接。</p><h2 id="常见问题" tabindex="-1">常见问题 <a class="header-anchor" href="#常见问题" aria-label="Permalink to &quot;常见问题&quot;">​</a></h2><h3 id="q-徽章不显示" tabindex="-1">Q: 徽章不显示？ <a class="header-anchor" href="#q-徽章不显示" aria-label="Permalink to &quot;Q: 徽章不显示？&quot;">​</a></h3><p>检查以下几点：</p><ol><li>配置 URL 是否可访问</li><li>配置格式是否正确</li><li>浏览器控制台是否有错误</li><li>徽章是否启用 (<code>enabled: true</code>)</li></ol><h3 id="q-如何调试" tabindex="-1">Q: 如何调试？ <a class="header-anchor" href="#q-如何调试" aria-label="Permalink to &quot;Q: 如何调试？&quot;">​</a></h3><p>启用调试模式：</p><div class="language-javascript line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang">javascript</span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">LinkExchange.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">mount</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;#badges&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  source: </span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;https://cdn.example.com/badges.json&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  telemetry: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">    enabled: </span><span style="${ssrRenderStyle({ "color": "#79B8FF" })}">true</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#B392F0" })}">    onEvent</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">: (</span><span style="${ssrRenderStyle({ "color": "#FFAB70" })}">event</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "color": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}"> console.</span><span style="${ssrRenderStyle({ "color": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "color": "#9ECBFF" })}">&#39;[Debug]&#39;</span><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">, event)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "color": "#E1E4E8" })}">})</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br><span class="line-number">4</span><br><span class="line-number">5</span><br><span class="line-number">6</span><br><span class="line-number">7</span><br></div></div><h3 id="q-如何处理-cors" tabindex="-1">Q: 如何处理 CORS？ <a class="header-anchor" href="#q-如何处理-cors" aria-label="Permalink to &quot;Q: 如何处理 CORS？&quot;">​</a></h3><p>确保配置服务器设置了正确的 CORS 头：</p><div class="language- line-numbers-mode"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki github-dark vp-code" tabindex="0"><code><span class="line"><span>Access-Control-Allow-Origin: *</span></span>
<span class="line"><span># 或指定域名</span></span>
<span class="line"><span>Access-Control-Allow-Origin: https://yourwebsite.com</span></span></code></pre><div class="line-numbers-wrapper" aria-hidden="true"><span class="line-number">1</span><br><span class="line-number">2</span><br><span class="line-number">3</span><br></div></div><h3 id="q-如何更新徽章" tabindex="-1">Q: 如何更新徽章？ <a class="header-anchor" href="#q-如何更新徽章" aria-label="Permalink to &quot;Q: 如何更新徽章？&quot;">​</a></h3><p>只需更新远程配置文件，SDK 会自动获取最新配置（受缓存 TTL 限制）。</p><h2 id="下一步" tabindex="-1">下一步 <a class="header-anchor" href="#下一步" aria-label="Permalink to &quot;下一步&quot;">​</a></h2><ul><li><a href="/LinkExchangeBadges/guide/configuration.html">配置选项</a></li><li><a href="/LinkExchangeBadges/guide/badge-rules.html">徽章规则</a></li><li><a href="/LinkExchangeBadges/guide/caching.html">缓存策略</a></li><li><a href="/LinkExchangeBadges/api/core.html">API 参考</a></li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("guide/getting-started.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const gettingStarted = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  gettingStarted as default
};
